background {
    monitor =
    path = ~/Pictures/wallpaper.png
    blur_passes = 2
}

input-field {
    monitor =
    size = 220, 50
    outline_thickness = 3
    outer_color = rgb(bd93f9) # Dracula Purple
    inner_color = rgb(282a36) # Dracula Background
    font_color = rgb(f8f8f2)  # Dracula White
    fade_on_empty = true
    placeholder_text = <i>Password...</i>
    position = 0, -20
    halign = center
    valign = center
}

label {
    monitor =
    text = $TIME
    color = rgb(8be9fd) # Dracula Cyan
    font_size = 64
    font_family = JetBrainsMono Nerd Font
    position = 0, 80
    halign = center
    valign = center
}
